# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "magento/", "/home/vagrant/magento",
  #   owner: "vagrant", group: "vagrant"

  config.ssh.pty = true

  # make sure the box has ansible installed
  # needing this depends on config.vm.box
  # config.vm.provision "shell", inline: "sudo apt-get update"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.inventory_path = "inventory/vagrant"
  end

end
