---
- name: Prep and configure
  hosts: vagrant
  user: "vagrant"
  become: yes
  become_method: sudo

  roles:
    - geerlingguy.php
    - geerlingguy.nginx
    - ansible-role-firewall
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - ansible-role-mysql
    - manual-cleanup
